name: Deploy us-east-2
on:
  push:
    tags:
      - v*
jobs:
  deploy_source:
    permissions:
      id-token: write
    name: Deploy source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install and build archive
        run: |
          yarn --production --pure-lockfile
          zip -rq9 bundle.zip . -x '*.git*'

      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#assuming-a-role
      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_OIDC_ROLE }}
          role-duration-seconds: 900
          aws-region: us-east-2

      - name: Update function code
        run: |
          aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --zip-file fileb://bundle.zip
